using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using GroupDocs.Annotation.Cloud.Sdk.Api;
using GroupDocs.Annotation.Cloud.Sdk.Model;
using GroupDocs.Annotation.Cloud.Sdk.Model.Requests;

namespace GroupDocs.Annotation.Cloud.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing ImageInfoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ImageInfoApiTests: TestsSetup
    {
        /// <summary>
        /// Test an instance of ImageInfoApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.IsInstanceOf(typeof(ImageInfoApi), _imageInfoApi, "instance is a ImageInfoApi");
        }
        /// <summary>
        /// Test GetInfo
        /// </summary>
        [Test]
        public void GetInfoTest()
        {
            GetInfoRequest request = new GetInfoRequest("one-page.pdf", "gfc-testdata/testsdata/groupdocs.annotation");
            var response = _imageInfoApi.GetInfo(request);
            Assert.IsInstanceOf<DocumentInfo>(response, "response is DocumentInfo");
        }
    }

}
