using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using GroupDocs.Annotation.Cloud.Sdk.Api;
using GroupDocs.Annotation.Cloud.Sdk.Model.Requests;

namespace GroupDocs.Annotation.Cloud.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing PdfFileApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PdfFileApiTests: TestsSetup
    {
        /// <summary>
        /// Test an instance of PdfFileApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.IsInstanceOf(typeof(PdfFileApi), _pdfFileApi, "instance is a PdfFileApi");
        }
        /// <summary>
        /// Test GetPdf
        /// </summary>
        [Test]
        public void GetPdfTest()
        {
            GetPdfRequest request = new GetPdfRequest("one-page.pdf", "gfc-testdata/testsdata/groupdocs.annotation");
            var response = _pdfFileApi.GetPdf(request);
            Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetPdfStream
        /// </summary>
        [Test]
        public void GetPdfStreamTest()
        {
            GetPdfStreamRequest request = new GetPdfStreamRequest("one-page.pdf", "gfc-testdata/testsdata/groupdocs.annotation");
            var response = _pdfFileApi.GetPdfStream(request);
            Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
    }

}
